import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import LayoutWrapper from '@/components/layout/LayoutWrapper';
import { ReduxProvider } from '@/store/provider';
import AuthIntializer from '@/components/AuthInitializer';
import { DriverProvider } from '@/components/dashboard/driver/DriverContext';
import { BookingProvider } from '@/components/dashboard/booking/BookingContext';
import { Toaster } from 'sonner';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pickyo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <AuthIntializer />

          <DriverProvider>
            <BookingProvider>
              <LayoutWrapper>
                {children}
                <Toaster position="top-right" richColors />
              </LayoutWrapper>
            </BookingProvider>
          </DriverProvider>

        </ReduxProvider>
      </body>
    </html>
  );
}
